---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ['private_network', {ip: '10.0.0.10'}]
  vagrantfile_erb: templates/Vagrantfile.erb

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.4

platforms:
  - name: centos-6.5
    driver:
      box: chef/centos-6.5

suites:
  - name: php-fpm
    run_list:
      - recipe[repo-helper]
      - recipe[php]
      - recipe[php-fpm]
    attributes:
      opsworks:
        ruby_stack: ruby
      php:
        install_method: package
        packages:
          - php
          - php-fpm
      php-fpm:
        service_name: php-fpm
        user: nginx
        group: nginx