AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

RedundantSelf:
  Enabled: false

UselessAssignment:
  Enabled: false

MethodLength:
  Enabled: false
